"""'Init'

Revision ID: f4f5d64b1aba
Revises: 480a65f62d21
Create Date: 2025-05-10 11:41:03.299028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f5d64b1aba'
down_revision: Union[str, None] = '480a65f62d21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        # sa.Column('confirmed', sa.Boolean(), nullable=False)
        sa.Column('confirmed', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
