# Generated by Django 5.2 on 2025-04-06 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quote', '0002_quote_user_author_alter_quote_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(fields=('fullname',), name='unique_tag_croos_all_users'),
        ),
    ]
